title:              Rubic
email:              baptiste.ossipow@gmail.com
description:        A Ruby theme
author:             bossip
baseurl:            "/"
url:                "https://poiesis.site/"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
