title:              Rubic
email:              baptiste.ossipow@gmail.com
description:        A Ruby theme
author:             bossip
baseurl:            "rubic"
url:                "https://bop.github.io/"
